services:
  psql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    volumes:
      - ${HOME}/.hvo/psql:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
