export enum Role {
  ADMIN = "ADMIN",
  VENDOR = "VENDOR",
  CREATOR = "CREATOR",
  STAFF = "STAFF",
  CREATOR_ASSISTANT = "CREATOR_ASSISTANT",
  ADMIN_ASSISTANT = "ADMIN_ASSISTANT",
  VENDOR_ASSISTANT = "VENDOR_ASSISTANT",
}

export enum StaffType {
  TRANSCRIPTOR = "TRANSCRIPTOR",
  TRANSLATOR = "TRANSLATOR",
  VOICE_ACTOR = "VOICE_ACTOR",
  AUDIO_ENGINEER = "AUDIO_ENGINEER",
}

export enum VideoStatus {
  BACKLOG = "BACKLOG",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
}

export enum AudioDubPhase {
  TRANSCRIPTION = "TRANSCRIPTION",
  TRANSLATION = "TRANSLATION",
  VOICE_OVER = "VOICE_OVER",
  AUDIO_ENGINEERING = "AUDIO_ENGINEERING",
}

export enum AudioDubProgress {
  TRANSCRIPTION = "TRANSCRIPTION",
  TRANSLATION = "TRANSLATION",
  VOICE_OVER = "VOICE_OVER",
  AUDIO_ENGINEERING = "AUDIO_ENGINEERING",
  REVIEW = "REVIEW",
}

export enum AudioDubStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  REVIEW = "REVIEW",
  COMPLETED = "COMPLETED",
}

export enum TaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FEEDBACK = "FEEDBACK",
}

export enum TaskType {
  TRANSCRIPTION = "TRANSCRIPTION",
  TRANSLATION = "TRANSLATION",
  VOICE_OVER = "VOICE_OVER",
  AUDIO_ENGINEERING = "AUDIO_ENGINEERING",
}

export enum FeedbackStatus {
  NEW = "NEW",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  REJECTED = "REJECTED",
}

export enum FeedbackIssueStatus {
  NEW = "NEW",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  REJECTED = "REJECTED",
}

export enum FeedbackPhase {
  UNKNOWN = "UNKNOWN",
  TRANSCRIPTION = "TRANSCRIPTION",
  TRANSLATION = "TRANSLATION",
  VOICE_OVER = "VOICE_OVER",
  AUDIO_ENGINEERING = "AUDIO_ENGINEERING",
}

export enum VideoProcessingStage {
  TRANSCODING = "TRANSCODING",
  BOX_UPLOAD = "BOX_UPLOAD",
  SONIX_UPLOAD = "SONIX_UPLOAD",
  VIDEO_TRANSCODING = "VIDEO_TRANSCODING",
  BOX_TO_GCS_TRANSFER = "BOX_TO_GCS_TRANSFER",
  GDRIVE_TO_GCS_TRANSFER = "GDRIVE_TO_GCS_TRANSFER",
  YOUTUBE_TO_GCS_TRANSFER = "YOUTUBE_TO_GCS_TRANSFER",
  OTHER = "OTHER",
}

export enum VideoProcessingIssueStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  IGNORED = "IGNORED",
}

export enum FormType {
  SHORT = "SHORT",
  LONG = "LONG",
}
